name: client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Paquetes de la app
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_stripe: ^11.2.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.0
  get: ^4.6.6
  get_storage: ^2.1.1
  share_plus: ^11.1.0
  http: ^1.5.0
  cached_network_image: ^3.4.1
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
